# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=128)),
                ('video_date', models.DateTimeField(blank=True, null=True)),
                ('retention', models.CharField(max_length=10)),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('content_type', models.CharField(default='xxx', max_length=50)),
            ],
        ),
    ]
