# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-20 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0002_auto_20170309_0327'),
        ('videomanagement', '0002_auto_20170317_2031'),
    ]

    operations = [
    ]
