# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0003_merge_20170320_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('make_public', 'make_public')], default='meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('extend_retention', 'extend_retention'), ('delete_video', 'delete_video')], default='extend_retention', max_length=50),
        ),
    ]
