# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0005_video_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gif',
            field=models.FileField(null=True, upload_to='gif'),
        ),
    ]
