# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0006_video_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gif',
            field=models.ImageField(null=True, upload_to='gif'),
        ),
    ]
