# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0007_auto_20170405_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='type',
            field=models.CharField(choices=[('meeting', 'meeting'), ('make_public', 'make_public'), ('inspect_video', 'inspect_video')], default='meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='retention',
            field=models.IntegerField(),
        ),
    ]
