# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0007_auto_20170405_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='retention',
            field=models.IntegerField(),
        ),
    ]
