# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-13 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0008_auto_20170413_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(choices=[('Gates Center for Computer Science', 'Gates Center for Computer Science'), ('Cyert Hall', 'Cyert Hall')], default='Gates Center for Computer Science', max_length=128),
        ),
    ]
