# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0011_auto_20170413_1933'),
        ('videomanagement', '0008_auto_20170414_0415'),
    ]

    operations = [
    ]
