# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0014_committeeaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeaction',
            name='request_date',
        ),
        migrations.RemoveField(
            model_name='committeeaction',
            name='video',
        ),
        migrations.AddField(
            model_name='committeeaction',
            name='request_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committeeaction',
            name='video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
