# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 04:10
from __future__ import unicode_literals

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0015_auto_20170419_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=django_encrypted_filefield.fields.EncryptedFileField(blank=True, upload_to='videos'),
        ),
    ]
