# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-22 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0015_auto_20170419_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
