# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 04:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0016_auto_20170422_0317'),
        ('videomanagement', '0016_auto_20170423_0410'),
    ]

    operations = [
    ]
