# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0017_auto_20170425_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingrequest',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
