# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0017_merge_20170423_0444'),
        ('videomanagement', '0018_auto_20170425_2009'),
    ]

    operations = [
    ]
