# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0019_merge_20170426_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='video_date',
            new_name='Date_That_Footage_Was_Recorded',
        ),
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='description',
            new_name='Description_of_Recorded_Event',
        ),
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='location',
            new_name='Location_of_Recorded_Event',
        ),
        migrations.RenameField(
            model_name='meetingrequest',
            old_name='reason_for_request',
            new_name='Reason_for_Request',
        ),
        migrations.RemoveField(
            model_name='meetingrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='meetingrequest',
            name='Type_of_Request',
            field=models.CharField(choices=[('make_public', 'Make The Referred Video Public'), ('inspect_video', 'Inspect a Video')], default='meeting', max_length=50),
        ),
        migrations.AlterField(
            model_name='committeeaction',
            name='type',
            field=models.CharField(choices=[('make_public', 'make_public'), ('inspect_video', 'inspect_video'), ('extend_retention', 'extend_retention'), ('privatize_video', 'privatize_video')], default='meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('extend_retention', 'Extend Retention Time'), ('privatize_video', 'Remove This Video from the Public Page'), ('register_complaint', 'Register a General Complaint')], default='extend_retention', max_length=50),
        ),
    ]
