# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0020_auto_20170428_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeeaction',
            name='type',
            field=models.CharField(choices=[('make_public', 'Make Video Public'), ('inspect_video', 'Inspect Video'), ('extend_retention', 'Extend Retention Time'), ('privatize_video', 'Make Video Private')], default='meeting', max_length=20),
        ),
    ]
