# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videomanagement', '0021_auto_20170501_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingrequest',
            name='Location_of_Recorded_Event',
            field=models.CharField(choices=[('Gates Center for Computer Science', 'Gates Center for Computer Science'), ('Cyert Hall', 'Cyert Hall'), ('Cohon University Center', 'Cohon University Center'), ('Hunt Library', 'Hunt Library'), ('Morewood Apartments', 'Morewood Apartments'), ('Other place', 'Other place')], default='Gates Center for Computer Science', max_length=128),
        ),
        migrations.AlterField(
            model_name='video',
            name='location',
            field=models.CharField(choices=[('Gates Center for Computer Science', 'Gates Center for Computer Science'), ('Cyert Hall', 'Cyert Hall'), ('Cohon University Center', 'Cohon University Center'), ('Hunt Library', 'Hunt Library'), ('Morewood Apartments', 'Morewood Apartments'), ('Other place', 'Other place')], default='Gates Center for Computer Science', max_length=128),
        ),
    ]
